# Generated by Django 5.0.2 on 2024-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute_logo", models.ImageField(upload_to="images/")),
                ("specialization", models.CharField(max_length=500)),
                ("institute", models.CharField(max_length=150)),
                ("gpa", models.CharField(max_length=10)),
                ("graduation_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_logo", models.ImageField(upload_to="images/")),
                ("project_title", models.CharField(max_length=150)),
                ("associated_to", models.CharField(max_length=150)),
                ("project_type", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("skills", models.JSONField()),
            ],
        ),
    ]
